# -*- coding: utf-8 -*-
"""Banco de preguntas A/B/C del curso «Conducción Segura y Manejo Defensivo».

Cada pregunta: (enunciado, correcta, distractor, distractor, fuente). La
correcta va siempre primero aquí; el generador la reparte entre A, B y C.
Todo sale de lo que muestran los videos (láminas y narración de las Partes 1 a
3); la evaluación final añade el caso integrador de la lámina 52 del PPTX.
"""

CURSO = {
    "nombre": "Conducción Segura y Manejo Defensivo",
    "descripcion": ("Curso de quince videos para trabajadores que conducen vehículos automotores en actividades "
                    "laborales, articulado con el PESV y el SG-SST. Abarca el riesgo vial laboral, la responsabilidad "
                    "legal, la inspección preoperacional, la posición de manejo, el manejo defensivo, la velocidad y "
                    "la distancia, las intersecciones y los adelantamientos, las distracciones, la fatiga, el alcohol "
                    "y los medicamentos, las condiciones adversas y la actuación ante un siniestro, con un cierre "
                    "sobre el marco jurídico. Al final hay una evaluación de 10 preguntas de selección múltiple."),
}

VIDEOS = [
    ("ap1", "Apertura 1", "Presentación y objetivo del curso", [
        ("¿A quién está dirigido el curso?",
         "A trabajadores que conducen vehículos automotores en actividades laborales.",
         "Solo a conductores de transporte público de pasajeros.",
         "A cualquier persona que quiera obtener su licencia de conducción.",
         "Diapositiva «Conducción Segura y Manejo Defensivo» (portada)"),
        ("¿Con qué sistemas de gestión se articula el curso?",
         "Con el Plan Estratégico de Seguridad Vial (PESV) y el SG-SST.",
         "Con el sistema de gestión de calidad y el de gestión ambiental.",
         "Solo con el reglamento interno de trabajo.",
         "Diapositiva «Conducción Segura y Manejo Defensivo» (portada)"),
        ("¿Cuál es el propósito central del curso?",
         "Desarrollar criterio vial: leer la situación, anticipar lo que puede ocurrir y elegir la maniobra más segura.",
         "Memorizar las normas de tránsito para aprobar un examen.",
         "Aprender mecánica básica para reparar el vehículo en la vía.",
         "Diapositiva «Objetivo general del curso»"),
        ("¿Cuáles son las cuatro competencias que desarrolla el curso?",
         "Percibir, anticipar, decidir y ejecutar.",
         "Acelerar, frenar, girar y estacionar.",
         "Conocer, memorizar, repetir y aprobar.",
         "Diapositiva «Objetivo general del curso»"),
        ("¿Qué significa la competencia «anticipar»?",
         "Prever lo que puede ocurrir enseguida en la vía.",
         "Salir con anticipación para llegar antes al destino.",
         "Adelantar a los vehículos lentos lo antes posible.",
         "Diapositiva «Objetivo general del curso»"),
        ("¿Cuál es la secuencia defensiva que acompaña todo el curso?",
         "Observar → identificar → anticipar → decidir → actuar.",
         "Acelerar → señalizar → girar → frenar → detenerse.",
         "Decidir → actuar → observar → corregir → reportar.",
         "Diapositiva «Objetivo general del curso»"),
    ]),
    ("ap2", "Apertura 2", "Ruta formativa: 12 módulos", [
        ("¿Cuántos módulos tiene la ruta formativa del curso?",
         "Doce módulos.",
         "Seis módulos.",
         "Cuatro módulos.",
         "Diapositiva «Ruta formativa: 12 módulos»"),
        ("¿Qué combina cada módulo del curso?",
         "Caso real, concepto técnico, norma aplicable, técnica segura y evaluación con retroalimentación inmediata.",
         "Únicamente la lectura de la norma de tránsito vigente.",
         "Solo videos de siniestros reales sin explicación técnica.",
         "Diapositiva «Ruta formativa: 12 módulos»"),
        ("¿Qué abordan los módulos sobre la condición del conductor?",
         "Distracciones, fatiga y sueño, y alcohol, drogas y medicamentos.",
         "Documentos del vehículo y trámites de tránsito.",
         "Rutas, horarios y tarifas de los desplazamientos.",
         "Diapositiva «Ruta formativa: 12 módulos»"),
        ("¿Con qué módulo termina la ruta formativa?",
         "Emergencias y siniestros.",
         "Riesgo vial laboral.",
         "Posición y control.",
         "Diapositiva «Ruta formativa: 12 módulos»"),
    ]),
    ("m01", "Módulo 1", "El conductor como actor vial y el riesgo vial laboral", [
        ("¿Qué es un actor vial?",
         "Una persona que participa en el sistema de tránsito y cuyas decisiones afectan a los demás.",
         "Solo el conductor profesional con licencia de categoría C.",
         "La autoridad de tránsito que controla la vía.",
         "Parte 1 · «Exposición vial laboral»"),
        ("¿Qué define la exposición vial laboral?",
         "La actividad que se realiza, no la propiedad del vehículo.",
         "Que el vehículo sea de propiedad de la empresa.",
         "Que el desplazamiento supere los cincuenta kilómetros.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuál de estos desplazamientos hace parte de la exposición vial laboral?",
         "Una visita comercial en el vehículo propio del trabajador.",
         "El paseo familiar de fin de semana.",
         "El viaje de vacaciones del trabajador.",
         "Parte 1 · «Exposición vial laboral»"),
        ("¿Qué es un peligro?",
         "Una condición que puede causar daño, como la lluvia o un neumático liso; por sí sola no genera siniestro.",
         "El choque o volcamiento que resulta de una pérdida de control.",
         "La sanción que impone la autoridad de tránsito.",
         "Parte 1 · tarjeta «Peligro»"),
        ("¿Qué es el riesgo?",
         "La combinación de una condición de peligro con el comportamiento del conductor.",
         "El resultado final de un choque.",
         "La probabilidad de recibir un comparendo.",
         "Parte 1 · tarjeta «Riesgo»"),
        ("¿Cuáles son los factores del modelo de riesgo vial?",
         "Conductor, vehículo, vía, entorno y organización.",
         "Solo el conductor y el vehículo.",
         "Velocidad, clima y hora del día.",
         "Parte 1 · franja «Modelo de factores»"),
        ("En la cadena del siniestro, ¿qué representa la velocidad inadecuada?",
         "El comportamiento inseguro.",
         "La condición de peligro.",
         "El siniestro.",
         "Parte 2 · «Peligro, riesgo y siniestro»"),
        ("¿Cómo se gestiona el riesgo vial laboral?",
         "Como cualquier otro peligro ocupacional: se identifica, se evalúa, se interviene y se verifica.",
         "Solo con la compra de un seguro para el vehículo.",
         "Dejándolo en manos de la experiencia de cada conductor.",
         "Parte 2 · «Cómo se controla»"),
        ("¿Cuál es la técnica segura antes de un desplazamiento laboral?",
         "Planear la ruta, el tiempo y los descansos antes de salir.",
         "Salir cuanto antes y decidir la ruta en el camino.",
         "Seguir siempre la ruta más corta sin importar las condiciones.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("Un trabajador debe usar su moto propia para una visita, llueve y el tiempo asignado es corto. ¿Cuál es la opción segura?",
         "Informar y reprogramar el desplazamiento.",
         "Salir igual y compensar el tiempo con más velocidad.",
         "Salir, porque en vehículo propio no hay exposición laboral.",
         "Parte 3 · «Decisión crítica»"),
    ]),
    ("m02", "Módulo 2", "Responsabilidad legal del conductor y normas de tránsito", [
        ("¿Qué documentos debe tener vigentes el conductor antes de cada desplazamiento?",
         "Licencia de conducción, SOAT y revisión técnico-mecánica cuando corresponda.",
         "Solo la cédula de ciudadanía.",
         "Únicamente la tarjeta de propiedad del vehículo.",
         "Parte 1 · tarjeta «Documentos»"),
        ("¿Dónde aplican las normas de tránsito?",
         "En la vía pública, en la vía privada abierta al público y en las vías privadas con circulación interna.",
         "Solo en las vías públicas urbanas.",
         "Solo en carreteras nacionales.",
         "Parte 1 · franja de aplicación de la norma"),
        ("¿Quiénes son los actores viales vulnerables con prelación expresa?",
         "Peatones, ciclistas, motociclistas y usuarios de micromovilidad.",
         "Los conductores de vehículos de carga.",
         "Los vehículos oficiales.",
         "Parte 1 · tarjeta «Actores vulnerables»"),
        ("¿Qué condición debe cumplir la licencia de conducción?",
         "Corresponder a la categoría del vehículo que se conduce.",
         "Tener al menos diez años de expedida.",
         "Estar expedida en la misma ciudad de la empresa.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué tipos de consecuencias puede tener una infracción de tránsito?",
         "Administrativas, laborales, civiles y penales.",
         "Solo administrativas, es decir, el comparendo.",
         "Solo laborales dentro de la empresa.",
         "Parte 2 · «Consecuencias posibles»"),
        ("¿Qué separación mínima exige la Ley 2486 de 2025 al adelantar ciclistas?",
         "1,50 metros.",
         "50 centímetros.",
         "3 metros.",
         "Parte 2 · tarjeta «Norma»"),
        ("¿Cuál es la técnica segura para maniobrar?",
         "Señalizar, comprobar espejos y punto ciego, y maniobrar sin cerrar a nadie.",
         "Maniobrar primero y señalizar después.",
         "Confiar en que los demás conductores cederán el paso.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("¿Por qué es un error suponer que en vía privada no aplican las normas?",
         "Porque la vía interna también es vía y la responsabilidad no termina al entrar a un patio privado.",
         "Porque en vía privada las multas son más altas.",
         "Porque en vía privada solo pueden circular vehículos de la empresa.",
         "Parte 3 · «Errores frecuentes»"),
        ("El vehículo tiene la revisión técnico-mecánica vencida ese mismo día y la entrega ya está programada. ¿Qué se debe hacer?",
         "No transitar y reportar la novedad.",
         "Hacer la entrega y renovar la revisión al regreso.",
         "Transitar solo por vías secundarias para evitar controles.",
         "Parte 3 · «Decisión crítica»"),
        ("Según el video, ¿qué es cumplir la norma?",
         "El mínimo del comportamiento seguro, no un trámite.",
         "Un trámite administrativo sin relación con la seguridad.",
         "Una responsabilidad exclusiva de la empresa.",
         "Parte 3 · franja final"),
    ]),
    ("m03", "Módulo 3", "Inspección preoperacional del vehículo", [
        ("¿Cuál es la metodología de la inspección preoperacional?",
         "Miro, verifico, reporto y decido, siempre en el mismo orden.",
         "Firmo, archivo, arranco y conduzco.",
         "Arranco, escucho, corrijo y continúo.",
         "Parte 1 · tarjeta «Metodología»"),
        ("¿Qué se revisa en los neumáticos durante la inspección?",
         "Presión, profundidad, cortes y el estado del repuesto.",
         "Solo el color y la marca.",
         "Únicamente el año de fabricación.",
         "Parte 1 · «Qué revisar»"),
        ("¿Qué incluye la revisión de seguridad del vehículo?",
         "Frenos, dirección, cinturones y testigos del tablero.",
         "Radio, aire acondicionado y tapicería.",
         "Solo el nivel de combustible.",
         "Parte 1 · «Qué revisar»"),
        ("Ante una condición crítica en frenos, dirección, luces o neumáticos, ¿qué se hace?",
         "No se inicia el desplazamiento.",
         "Se inicia el viaje a baja velocidad.",
         "Se anota en el formato y se continúa.",
         "Parte 1 · franja «Miro – verifico – reporto – decido»"),
        ("¿Por qué conviene detectar las fallas antes de mover el vehículo?",
         "Porque corregir en el patio es barato; en la vía no.",
         "Porque así se evita diligenciar el formato.",
         "Porque el mantenimiento preventivo lo cubre todo.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuál de estos elementos hace parte del equipo de carretera obligatorio?",
         "Botiquín y extintor.",
         "Radio y cargador del celular.",
         "Parasol y ambientador.",
         "Parte 2 · «Equipo de carretera»"),
        ("¿Qué pasa si falta el equipo de carretera?",
         "Su ausencia impide la circulación.",
         "Solo se recibe una recomendación verbal.",
         "Puede circularse si el trayecto es corto.",
         "Parte 2 · tarjeta «Norma»"),
        ("¿Cuál es la técnica segura antes de abordar el vehículo?",
         "Hacer un recorrido perimetral del vehículo.",
         "Encender el motor y esperar que se caliente.",
         "Revisar solo el tablero una vez en marcha.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("El tablero muestra una alerta de baja presión, la ruta es larga y el cliente espera. ¿Cuál es la opción segura?",
         "Inspeccionar y no iniciar si la condición es crítica.",
         "Salir igual y revisar en la primera estación.",
         "Ignorar la alerta porque puede ser un error del sensor.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Qué error señala el video sobre el formato de inspección?",
         "Firmar el formato sin revisar el vehículo: firmar no vuelve seguro un vehículo que no lo está.",
         "Diligenciar el formato con demasiado detalle.",
         "Entregar el formato al supervisor.",
         "Parte 3 · «Errores frecuentes»"),
    ]),
    ("m04", "Módulo 4", "Posición segura y control del vehículo", [
        ("¿Cómo debe quedar el ajuste del asiento respecto a los pedales y el volante?",
         "Pedales a fondo sin estirar la pierna y brazos ligeramente flexionados.",
         "Lo más reclinado posible para mayor comodidad.",
         "Lo más cerca posible del volante, con los brazos doblados al máximo.",
         "Parte 1 · tarjeta «Ajuste»"),
        ("¿Cuándo se ajustan asiento, volante y espejos?",
         "Con el vehículo detenido, antes de arrancar.",
         "Durante la marcha, en el primer semáforo.",
         "Una vez al mes en el mantenimiento.",
         "Parte 1 · tarjeta «Ajuste»"),
        ("¿Qué previene el apoyacabezas a la altura correcta?",
         "Lesiones cervicales.",
         "La fatiga visual.",
         "El deslumbramiento nocturno.",
         "Parte 1 · «Por qué importa»"),
        ("¿Eliminan los espejos los puntos ciegos?",
         "No: amplían el campo visual, pero el giro de cabeza sigue siendo obligatorio.",
         "Sí, si están bien regulados.",
         "Sí, en los vehículos modernos.",
         "Parte 1 · tarjeta «Espejos»"),
        ("¿Por qué importa la postura del conductor?",
         "Porque una mala posición retrasa la reacción y el control real depende de la postura.",
         "Solo por comodidad en viajes largos.",
         "Porque lo exige el fabricante para la garantía.",
         "Parte 1 · «Por qué importa»"),
        ("¿Quién debe usar el cinturón de seguridad?",
         "El conductor y todos los acompañantes, en ciudad y en carretera.",
         "Solo el conductor en carretera.",
         "Solo los acompañantes del asiento delantero.",
         "Parte 2 · tarjeta «Norma»"),
        ("¿Qué pasa con los objetos sueltos en una colisión?",
         "Botellas, herramientas y computadores se vuelven proyectiles.",
         "Se quedan en su sitio por el peso.",
         "Solo representan un problema de orden.",
         "Parte 2 · «Cinturón y objetos sueltos»"),
        ("¿Cuándo se configura el GPS?",
         "Antes de iniciar la marcha.",
         "En el primer tramo recto de la vía.",
         "Mientras se espera en un semáforo.",
         "Parte 2 · «Antes de arrancar»"),
        ("Recorrido de diez minutos entre dos sedes y el acompañante no se abrocha el cinturón. ¿Qué se hace?",
         "No arrancar hasta asegurar a todos.",
         "Arrancar, porque el trayecto es corto.",
         "Arrancar y pedirle que se lo ponga en carretera.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Por qué es un error creer que el trayecto corto no requiere protección?",
         "Porque la energía del impacto no depende de la distancia y la mayoría de siniestros ocurre cerca del origen.",
         "Porque en trayectos cortos la velocidad siempre es alta.",
         "Porque el seguro no cubre trayectos cortos.",
         "Parte 3 · tarjeta «Error frecuente»"),
    ]),
    ("m05", "Módulo 5", "Manejo defensivo: ver, anticipar y decidir", [
        ("¿Qué significa conducir defensivamente?",
         "No depender de que el otro haga lo correcto; no significa conducir lento.",
         "Conducir siempre por debajo de 30 km/h.",
         "Imponer la prioridad para que los demás respeten.",
         "Parte 1 · franja «Conducir defensivamente…»"),
        ("¿Dónde debe estar la mirada del conductor defensivo?",
         "Al final de la vía, con visión periférica activa.",
         "Fija en el vehículo de adelante.",
         "En el tablero, para controlar la velocidad.",
         "Parte 1 · tarjeta «Visión»"),
        ("¿Qué ocurre si se interrumpe la secuencia defensiva?",
         "Desaparece el margen de reacción.",
         "Aumenta la visibilidad.",
         "No pasa nada si el conductor tiene experiencia.",
         "Parte 1 · tarjeta «Secuencia»"),
        ("¿Cuál de estas es una habilidad defensiva?",
         "Identificar rutas de escape.",
         "Seguir de cerca al vehículo de adelante.",
         "Confiar en la prioridad.",
         "Parte 1 · «Habilidades defensivas»"),
        ("¿Por qué el error ajeno se considera previsible?",
         "Porque anticiparlo entrega segundos de margen para reaccionar.",
         "Porque siempre lo cometen los mismos conductores.",
         "Porque la norma obliga a los demás a avisar.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuál de estas es una amenaza frecuente en la vía?",
         "Una puerta que se abre desde un vehículo estacionado.",
         "Un semáforo en verde.",
         "Una vía recta y seca.",
         "Parte 2 · «Amenazas frecuentes»"),
        ("¿Cuál es la técnica segura del manejo defensivo?",
         "Mantener siempre una ruta de escape libre.",
         "Circular pegado al vehículo de adelante.",
         "Cambiar de carril con frecuencia.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("¿Cuál es la regla base del manejo defensivo?",
         "Asumir que los demás pueden equivocarse.",
         "Asumir que los demás siempre respetan la norma.",
         "Asumir que la experiencia evita los errores.",
         "Parte 2 · tarjeta «Regla»"),
        ("Un vehículo estacionado enciende la direccional y un peatón cruza entre dos automóviles. ¿Qué se hace?",
         "Liberar el acelerador y abrir espacio.",
         "Mantener la velocidad y pitar.",
         "Acelerar para pasar antes de que salga el vehículo.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Qué error frecuente señala el video sobre los otros conductores?",
         "Suponer que el otro conductor ya vio el vehículo.",
         "Mantener la distancia de seguimiento.",
         "Hacer el giro de cabeza antes de cambiar de carril.",
         "Parte 3 · tarjeta «Error frecuente»"),
    ]),
    ("m06", "Módulo 6", "Velocidad segura y distancia de seguridad", [
        ("¿Cuál es la velocidad segura?",
         "La que permite detenerse dentro del espacio que se alcanza a ver; puede ser menor que el límite.",
         "Siempre la velocidad máxima señalizada.",
         "La que mantiene el flujo del tráfico.",
         "Parte 1 · tarjeta «Velocidad segura»"),
        ("¿Qué diferencia hay entre el límite legal y la velocidad segura?",
         "El límite es legal; la velocidad segura depende de las condiciones reales.",
         "No hay diferencia: son lo mismo.",
         "La velocidad segura siempre es mayor que el límite.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué sucede con el campo visual al aumentar la velocidad?",
         "Se reduce.",
         "Aumenta.",
         "No cambia.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué suma la distancia total de detención?",
         "Percepción, reacción y frenado.",
         "Solo la distancia de frenado.",
         "La longitud del vehículo y la del de adelante.",
         "Parte 2 · «Distancias de detención»"),
        ("¿Cómo se aplica la técnica de los tres segundos?",
         "Se elige un punto fijo y se cuentan tres segundos tras el vehículo de adelante.",
         "Se frena durante tres segundos antes de cada curva.",
         "Se mira el espejo cada tres segundos.",
         "Parte 2 · «Cómo aplicarlo»"),
        ("¿Cuándo debe aumentarse el conteo de segundos de separación?",
         "Con lluvia o con carga.",
         "Solo de noche en vías urbanas.",
         "Nunca: tres segundos sirven para todo.",
         "Parte 2 · «Cómo aplicarlo»"),
        ("¿Cuál es la técnica segura sobre la velocidad?",
         "Ajustar antes de que cambie la condición: se frena antes, no durante.",
         "Frenar dentro de la curva para corregir.",
         "Acelerar al salir de la lluvia para recuperar tiempo.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("¿Por qué conviene medir la distancia en segundos y no en metros?",
         "Porque los segundos se ajustan solos a la velocidad.",
         "Porque los metros son difíciles de ver.",
         "Porque la norma prohíbe medir en metros.",
         "Parte 3 · tarjeta «Error frecuente»"),
        ("Lluvia intensa, tráfico a 80 km/h y una entrega retrasada veinte minutos. ¿Cuál es la opción segura?",
         "Reducir la velocidad y ampliar la separación.",
         "Mantener la velocidad para no perder más tiempo.",
         "Acelerar un poco para recuperar el retraso.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Ir por debajo del límite garantiza una velocidad segura?",
         "No: la velocidad segura depende de las condiciones.",
         "Sí, siempre.",
         "Sí, si la vía es urbana.",
         "Parte 3 · franja final"),
    ]),
    ("m07", "Módulo 7", "Intersecciones, adelantamientos y puntos ciegos", [
        ("¿Por qué las intersecciones son puntos críticos?",
         "Porque concentran los siniestros al converger trayectorias en un mismo espacio.",
         "Porque siempre tienen semáforo.",
         "Porque en ellas no aplica la prioridad.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cómo debe aproximarse el conductor a una intersección?",
         "Reduciendo de forma preventiva, observando a ambos lados y sin ingresar sin salida libre.",
         "Acelerando para cruzar antes de que cambie el semáforo.",
         "Manteniendo la velocidad si tiene prioridad.",
         "Parte 1 · tarjeta «Aproximación»"),
        ("¿Qué indica no ver el espejo de un camión o bus?",
         "Que su conductor no lo ve a usted: está en su punto ciego.",
         "Que el camión va a detenerse.",
         "Que el espejo está mal regulado y no importa.",
         "Parte 1 · tarjeta «Puntos ciegos»"),
        ("¿Qué genera bloquear un cruce?",
         "Nuevos conflictos en la intersección.",
         "Mayor fluidez del tráfico.",
         "Prioridad para el vehículo que bloquea.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué debe comprobarse antes de adelantar?",
         "La necesidad real, la visibilidad y la distancia disponible, y el retorno seguro al carril.",
         "Solo que el vehículo de adelante vaya lento.",
         "Que no haya policía de tránsito.",
         "Parte 2 · «Antes de adelantar»"),
        ("¿Cuándo se regresa al carril tras adelantar?",
         "Cuando el vehículo adelantado se vea completo en el espejo.",
         "Apenas se pase la trompa del otro vehículo.",
         "Cuando el otro conductor haga cambio de luces.",
         "Parte 2 · «Antes de adelantar»"),
        ("¿Dónde está prohibido adelantar?",
         "En curva, puente, túnel o línea continua.",
         "En cualquier vía de doble carril.",
         "Solo en zonas escolares.",
         "Parte 2 · tarjeta «Norma»"),
        ("¿Cuál es la técnica segura antes de cada maniobra lateral?",
         "El giro de cabeza, porque el espejo no cubre todo el costado.",
         "Pitar dos veces.",
         "Encender las luces de emergencia.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("Vía de doble sentido, un camión lento adelante y una curva próxima. ¿Qué se hace?",
         "Esperar un tramo recto y visible para adelantar.",
         "Adelantar rápido antes de la curva.",
         "Adelantar siguiendo a otro vehículo que ya lo está haciendo.",
         "Parte 3 · «Decisión crítica»"),
        ("Según el video, ¿cuándo una maniobra no es segura?",
         "Cuando necesita suerte para salir bien.",
         "Cuando se hace con luces encendidas.",
         "Cuando se hace a baja velocidad.",
         "Parte 3 · franja final"),
    ]),
    ("m08", "Módulo 8", "Distracciones al conducir", [
        ("¿Cuáles son los cuatro tipos de distracción?",
         "Visual, manual, cognitiva y auditiva.",
         "Diurna, nocturna, urbana y rural.",
         "Leve, moderada, grave y mortal.",
         "Parte 1 · «Cuatro tipos de distracción»"),
        ("¿Qué es la distracción cognitiva?",
         "Dejar de concentrarse en la conducción.",
         "Apartar los ojos de la vía.",
         "Retirar las manos del volante.",
         "Parte 1 · «Cuatro tipos de distracción»"),
        ("¿Qué tipos de distracción implica leer un mensaje?",
         "Los cuatro a la vez.",
         "Solo la visual.",
         "Solo la auditiva.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuánto se avanza a ciegas en tres segundos mirando el celular?",
         "Unos cincuenta metros.",
         "Unos cinco metros.",
         "Menos de un metro.",
         "Parte 1 · tarjeta «Costo»"),
        ("¿Cómo funciona la atención al conducir?",
         "No se divide, se alterna: el cerebro alterna, no multiplica.",
         "Se divide sin problema entre varias tareas.",
         "Mejora cuando se hacen varias cosas a la vez.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuál es una alternativa segura frente al celular?",
         "Activar el modo conducción y detenerse en un lugar permitido para responder.",
         "Responder solo con mensajes de voz en marcha.",
         "Usar el celular únicamente en los semáforos.",
         "Parte 2 · «Alternativas seguras»"),
        ("¿Qué responsabilidad tiene la organización frente a las distracciones?",
         "No exigir respuestas inmediatas a quien conduce: la presión también es un distractor.",
         "Exigir que el conductor esté siempre disponible por teléfono.",
         "Ninguna: la distracción es un asunto personal.",
         "Parte 2 · tarjeta «Organización»"),
        ("¿Justifica una llamada laboral el uso del celular mientras se conduce?",
         "No: una llamada laboral no convierte en seguro su uso.",
         "Sí, si es del jefe.",
         "Sí, si la llamada dura menos de un minuto.",
         "Parte 2 · franja"),
        ("Llega un mensaje urgente del jefe a treinta minutos del destino. ¿Cuál es la opción segura?",
         "Detenerse en un sitio permitido para responder.",
         "Responder en marcha, porque es urgente.",
         "Responder en el siguiente semáforo en rojo.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Cuál de estas conductas es un error frecuente?",
         "Responder mensajes en el semáforo.",
         "Configurar el GPS antes de arrancar.",
         "Delegar las llamadas mientras se conduce.",
         "Parte 3 · «Errores frecuentes»"),
    ]),
    ("m09", "Módulo 9", "Fatiga, sueño y condiciones del conductor", [
        ("¿Cuál de estas es una señal de alarma de fatiga?",
         "Olvidar los kilómetros recientes.",
         "Sentir hambre.",
         "Tener frío.",
         "Parte 1 · «Señales de alarma»"),
        ("¿Qué es el microsueño?",
         "Un episodio de pocos segundos en el que se pierde el control sin que el conductor se dé cuenta.",
         "Una siesta corta y planeada en una pausa.",
         "Un bostezo prolongado.",
         "Parte 1 · tarjeta «Microsueño»"),
        ("¿Cuánto se recorre en cuatro segundos de microsueño a 80 km/h?",
         "Unos noventa metros.",
         "Unos diez metros.",
         "Unos quinientos metros.",
         "Parte 1 · «Por qué importa»"),
        ("¿Sustituyen el café, la música fuerte o abrir la ventana al descanso?",
         "No: la única solución es detenerse y dormir.",
         "Sí, si se combinan los tres.",
         "Sí, en trayectos cortos.",
         "Parte 1 · franja"),
        ("¿Qué pasa con el sueño acumulado?",
         "Se acumula y no se compensa.",
         "Se compensa con un café.",
         "Desaparece al empezar a conducir.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cuál de estos es un factor organizacional de fatiga?",
         "Itinerarios imposibles de cumplir.",
         "El color del vehículo.",
         "La marca de los neumáticos.",
         "Parte 2 · «Factores organizacionales»"),
        ("¿Cada cuánto deben planearse las pausas?",
         "Cada dos horas.",
         "Cada seis horas.",
         "Solo al llegar al destino.",
         "Parte 2 · «Cómo prevenir»"),
        ("¿Cuál es la técnica segura ante la fatiga?",
         "Una pausa de quince a veinte minutos o una siesta corta.",
         "Subir el volumen de la radio.",
         "Aumentar la velocidad para llegar antes.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("Cuatro horas de sueño, cuatro horas de ruta y un compromiso de llegada temprano. ¿Qué se hace?",
         "Reprogramar o descansar antes de iniciar el viaje.",
         "Salir y tomar café durante el camino.",
         "Salir más rápido para llegar con tiempo de descansar.",
         "Parte 3 · «Decisión crítica»"),
        ("¿A qué se compara conducir con sueño?",
         "Deteriora como el alcohol.",
         "No tiene efecto si hay experiencia.",
         "Solo afecta de noche.",
         "Parte 3 · «Decisión crítica»"),
    ]),
    ("m10", "Módulo 10", "Alcohol, drogas y medicamentos", [
        ("¿Qué efectos tienen el alcohol y los psicoactivos en el conductor?",
         "Alteran percepción, juicio y coordinación y aumentan el tiempo de reacción.",
         "Mejoran la concentración.",
         "Reducen el tiempo de reacción.",
         "Parte 1 · «Alcohol y psicoactivos»"),
        ("¿Qué falsa sensación genera el alcohol?",
         "Da confianza y quita capacidad: falsa sensación de control.",
         "Sensación de cansancio que obliga a detenerse.",
         "Ninguna: sus efectos son evidentes para el conductor.",
         "Parte 1 · «Por qué importa»"),
        ("¿Terminan los efectos del alcohol al dejar de consumir?",
         "No: los efectos persisten después del consumo.",
         "Sí, de inmediato.",
         "Sí, después de una comida.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué medicamentos pueden afectar los reflejos?",
         "Antihistamínicos, relajantes y ansiolíticos.",
         "Solo los medicamentos sin fórmula.",
         "Ninguno, si es formulado por un médico.",
         "Parte 1 · tarjeta «Medicamentos»"),
        ("¿Ser legal hace compatible un medicamento con conducir?",
         "No: ser legales no los hace compatibles con la conducción.",
         "Sí, siempre.",
         "Sí, si se toma en la mañana.",
         "Parte 1 · tarjeta «Medicamentos»"),
        ("¿Qué política aplica la organización frente al alcohol?",
         "Tolerancia cero.",
         "Tolerancia en trayectos cortos.",
         "Tolerancia los fines de semana.",
         "Parte 1 · «Por qué importa»"),
        ("¿Qué conducta se espera si un medicamento produce efectos?",
         "Informar al supervisor antes del turno y no iniciar la conducción.",
         "Conducir más despacio sin avisar.",
         "Tomar café para contrarrestar el efecto.",
         "Parte 2 · «Conducta esperada»"),
        ("¿Es una falta avisar a tiempo que un medicamento impide conducir?",
         "No: avisar a tiempo es una conducta segura y no constituye falta disciplinaria.",
         "Sí, genera una sanción.",
         "Sí, porque afecta la operación.",
         "Parte 2 · tarjeta «Reporte»"),
        ("Un medicamento formulado produce somnolencia y hay una ruta larga en la mañana. ¿Qué se hace?",
         "Informar y reprogramar el desplazamiento.",
         "Conducir igual con las ventanas abiertas.",
         "Suspender el medicamento por decisión propia.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Por qué no debe autoevaluarse la capacidad para conducir bajo efectos de una sustancia?",
         "Porque la sustancia altera el juicio con el que se haría esa evaluación.",
         "Porque la autoevaluación siempre es exagerada.",
         "Porque solo el médico de la ARL puede conducir.",
         "Parte 3 · franja final"),
    ]),
    ("m11", "Módulo 11", "Conducción en condiciones adversas", [
        ("¿Qué exige la lluvia al conductor?",
         "Menos velocidad y más distancia, por el riesgo de hidroplaneo.",
         "Más velocidad para salir rápido del aguacero.",
         "Luces altas encendidas.",
         "Parte 1 · «Clima y visibilidad»"),
        ("¿Qué es el hidroplaneo?",
         "La pérdida de contacto entre el neumático y el pavimento.",
         "El sobrecalentamiento de los frenos en bajada.",
         "El deslumbramiento por luces altas.",
         "Parte 1 · tarjeta «Hidroplaneo»"),
        ("¿Qué se hace ante un hidroplaneo?",
         "No frenar: soltar el acelerador y sostener el volante.",
         "Frenar a fondo de inmediato.",
         "Girar el volante bruscamente.",
         "Parte 1 · tarjeta «Hidroplaneo»"),
        ("¿Qué luces se usan con niebla?",
         "Luces bajas y exploradoras, nunca altas.",
         "Luces altas, para ver más lejos.",
         "Ninguna luz, para no encandilar.",
         "Parte 1 · tarjeta «Niebla»"),
        ("¿Cómo se controla un descenso?",
         "Con los cambios, sin abusar del freno.",
         "Con el freno sostenido todo el tiempo.",
         "En neutro, para ahorrar combustible.",
         "Parte 2 · «Vía y topografía»"),
        ("¿Cuál es la técnica segura en las curvas?",
         "Frenar antes de entrar, controlar dentro y acelerar a la salida.",
         "Frenar dentro de la curva.",
         "Acelerar al entrar a la curva.",
         "Parte 2 · tarjeta «Técnica segura»"),
        ("¿Qué riesgos agrega la conducción nocturna?",
         "Deslumbramiento, peatones poco visibles y animales en la vía.",
         "Ninguno, porque hay menos tráfico.",
         "Solo el consumo de combustible.",
         "Parte 2 · tarjeta «Noche»"),
        ("Cuando cambian las condiciones de la vía, ¿qué debe hacerse con la distancia de seguimiento?",
         "Aumentarla siempre.",
         "Reducirla para no perder de vista al de adelante.",
         "Mantenerla igual.",
         "Parte 2 · franja"),
        ("Aguacero fuerte en carretera de montaña, visibilidad reducida y carga completa. ¿Cuál es la opción segura?",
         "Reducir o detenerse en un sitio seguro.",
         "Continuar al mismo ritmo para llegar antes.",
         "Detenerse en la berma sin señalizar.",
         "Parte 3 · «Decisión crítica»"),
        ("Si el conductor se detiene durante la lluvia, ¿cómo debe hacerlo?",
         "Fuera del flujo vehicular y señalizando.",
         "En la berma, sin señalizar, por poco tiempo.",
         "En la mitad del carril con las luces apagadas.",
         "Parte 3 · tarjeta «Error frecuente»"),
    ]),
    ("m12", "Módulo 12", "Qué hacer ante una emergencia o siniestro vial", [
        ("¿Cuál es la secuencia básica ante una emergencia vial?",
         "Proteger → alertar → socorrer.",
         "Socorrer → discutir → reportar.",
         "Alertar → mover al lesionado → proteger.",
         "Parte 1 · franja «Proteger → Alertar → Socorrer»"),
        ("¿Qué implica «proteger»?",
         "Detenerse en condición segura, evitar nuevos choques y señalizar sin exponerse.",
         "Mover los vehículos antes de señalizar.",
         "Buscar al responsable del choque.",
         "Parte 1 · tarjeta «Proteger»"),
        ("¿Qué implica «alertar»?",
         "Activar la línea de emergencias y el protocolo interno, comunicando ubicación, involucrados y riesgos.",
         "Publicar el accidente en redes sociales.",
         "Esperar a que otra persona llame.",
         "Parte 1 · tarjeta «Alertar»"),
        ("¿Por qué es tan importante proteger la escena?",
         "Porque el segundo siniestro suele ser peor que el primero.",
         "Porque así se conserva la prioridad.",
         "Porque la aseguradora lo exige para pagar.",
         "Parte 1 · «Por qué importa»"),
        ("¿Cómo se socorre a un lesionado?",
         "Evaluando sin exponerse y sin movilizarlo, siguiendo instrucciones del personal especializado.",
         "Moviéndolo de inmediato a un lugar cómodo.",
         "Dándole agua y ayudándolo a caminar.",
         "Parte 2 · tarjeta «Socorrer»"),
        ("¿Qué información se reporta a la empresa tras el evento?",
         "Ubicación y hora, personas involucradas, daños, condiciones de vía y clima y evidencia disponible.",
         "Solo el nombre del otro conductor.",
         "Únicamente el valor estimado de los daños.",
         "Parte 2 · «Qué reportar a la empresa»"),
        ("¿Qué cierra el ciclo después del evento?",
         "La investigación, las acciones correctivas y las lecciones aprendidas.",
         "El pago del deducible.",
         "La firma del informe policial.",
         "Parte 2 · tarjeta «Después»"),
        ("Choque leve en vía de alto flujo y un ocupante con dolor cervical. ¿Qué se hace?",
         "No moverlo y activar los servicios de emergencia.",
         "Sacarlo del vehículo para revisarlo.",
         "Llevarlo al hospital en el mismo vehículo.",
         "Parte 3 · «Decisión crítica»"),
        ("¿Cuál de estas conductas es un error frecuente tras un siniestro?",
         "Discutir responsabilidades en el lugar.",
         "Señalizar el sitio del evento.",
         "Reportar a la organización.",
         "Parte 3 · «Errores frecuentes»"),
        ("Tras un siniestro, ¿cuál es la prioridad?",
         "Proteger la vida, no establecer la culpa.",
         "Establecer quién tuvo la culpa.",
         "Tomar fotos para la aseguradora.",
         "Parte 3 · franja final"),
    ]),
    ("cierre", "Cierre", "Marco jurídico y mensaje final", [
        ("¿Qué norma es el Código Nacional de Tránsito?",
         "La Ley 769 de 2002.",
         "La Ley 1503 de 2011.",
         "El Decreto 1079 de 2015.",
         "Diapositiva «Marco jurídico y técnico de referencia»"),
        ("¿Qué promueve la Ley 1503 de 2011?",
         "Comportamientos seguros en la vía e introduce la seguridad vial en el ámbito laboral.",
         "La separación de 1,50 m al adelantar ciclistas.",
         "Las multas por no portar el SOAT.",
         "Diapositiva «Marco jurídico y técnico de referencia»"),
        ("¿Qué establecen el Decreto 1079 de 2015 y la Resolución 20223040040595 de 2022?",
         "La metodología de diseño e implementación del PESV.",
         "Los límites de velocidad en carretera.",
         "Las categorías de la licencia de conducción.",
         "Diapositiva «Marco jurídico y técnico de referencia»"),
        ("¿A qué organizaciones aplica, en general, la obligación del PESV?",
         "A las que tienen flota superior a diez vehículos o contratan o administran conductores.",
         "Solo a las empresas de transporte público.",
         "A todas las empresas, sin excepción.",
         "Diapositiva «Marco jurídico y técnico de referencia»"),
        ("¿Cuál es la secuencia que resume el curso?",
         "Percibir, anticipar, decidir y ejecutar con seguridad.",
         "Acelerar, adelantar, llegar y reportar.",
         "Memorizar, repetir, aprobar y certificar.",
         "Diapositiva «Mensaje final»"),
        ("¿Cómo se reparte la responsabilidad de la seguridad vial?",
         "Es compartida: la organización planifica rutas, vehículos y jornadas, y el conductor decide en la vía.",
         "Es exclusiva del conductor.",
         "Es exclusiva de la empresa.",
         "Diapositiva «Mensaje final»"),
    ]),
]

FINAL = ("final", "Evaluación final", "Examen independiente", [
    ("Son las 5:30 a. m.; un trabajador durmió cuatro horas y debe conducir cuatro horas bajo lluvia. ¿Cuál es el primer riesgo que debe reconocer?",
     "Fatiga y privación de sueño.",
     "La falta de combustible.",
     "El tráfico de la ciudad de destino.",
     "Caso integrador · «Riesgos presentes» (PPTX)"),
    ("En ese mismo caso, el tablero muestra alerta de baja presión en un neumático. ¿Qué decisión se espera?",
     "Inspeccionar el neumático y no iniciar si la condición es crítica.",
     "Salir y revisarlo al llegar al destino.",
     "Aumentar la velocidad para llegar antes de que empeore.",
     "Caso integrador · «Decisiones correctas esperadas» (PPTX)"),
    ("El jefe envía un mensaje: debe llegar antes de las 9:00 a. m. ¿Cuál es la decisión correcta?",
     "Informar una posible demora sin asumir riesgos adicionales.",
     "Acelerar para cumplir el horario.",
     "Responder el mensaje mientras conduce.",
     "Caso integrador · «Decisiones correctas esperadas» (PPTX)"),
    ("Con lluvia durante el trayecto, ¿qué ajustes corresponden?",
     "Ajustar la velocidad y aumentar las distancias de seguimiento.",
     "Mantener la velocidad y la distancia habituales.",
     "Encender las luces altas y adelantar para salir de la lluvia.",
     "Caso integrador · «Decisiones correctas esperadas» (PPTX)"),
    ("¿Qué mide la evaluación final del curso?",
     "Criterio vial, no memoria.",
     "La memorización de artículos de la ley.",
     "La velocidad de respuesta del participante.",
     "Diapositiva «Evaluación final: caso integrador» (PPTX)"),
    ("¿El riesgo vial laboral solo existe cuando se conduce un vehículo de la empresa?",
     "No: la exposición depende de la actividad, no del propietario del vehículo.",
     "Sí, solo con vehículos de la empresa.",
     "Sí, salvo que el trabajador sea conductor profesional.",
     "Módulo 1 · «Por qué importa»"),
    ("Si se diligenció el formato de inspección, ¿puede viajarse con una falla crítica?",
     "No: el formato no elimina la condición insegura.",
     "Sí, porque el formato traslada la responsabilidad.",
     "Sí, si el supervisor lo firma.",
     "Módulo 3 · «Errores frecuentes»"),
    ("¿Cuándo debe aumentarse la distancia con el vehículo de adelante?",
     "Con lluvia, pavimento mojado o baja visibilidad.",
     "Solo cuando se circula por autopista.",
     "Nunca: la distancia es la misma en todas las condiciones.",
     "Módulo 6 · «Cómo aplicarlo»"),
    ("¿Se puede adelantar a un ciclista a menos de 1,50 m si se circula despacio?",
     "No: la distancia mínima no admite excepción por velocidad.",
     "Sí, si la velocidad es menor a 30 km/h.",
     "Sí, si el ciclista va por el borde de la vía.",
     "Módulo 7 · tarjeta «Norma»"),
    ("¿Cuál de estas es una señal de fatiga?",
     "Bostezos, salidas de carril y olvidar los kilómetros recientes.",
     "Sentir sed.",
     "Tener las manos frías.",
     "Módulo 9 · «Señales de alarma»"),
])
